matrix:
  include:

  - language: java
    jdk: oraclejdk8
    script:
      - CHANGED_FUNCTION=$(git diff --name-only HEAD^ | grep "dropbox-diary-function")
      - CHANGED_DESKTOP=$(git diff --name-only HEAD^ | grep "dropbox-diary-desktop")
      - "echo ${CHANGED_FUNCTION}"
      - "echo ${CHANGED_DESKTOP}"
      - "./gradlew clean build"
    deploy:

    # Deploy Dropbox Diary function lib to AWS Lambda
    - provider: lambda
      function_name: dropbox-diary-function
      region: us-east-1
      role: arn:aws:iam::377159598624:role/aws-lambda-deployer # see https://docs.travis-ci.com/user/deployment/lambda/#AWS-permissions
      runtime: java8
      zip: dropbox-diary-function/build/distributions/dropbox-diary-function.zip
      module_name: kadiary # package name
      handler_name: Main # class name
      timeout: 60 # seconds
      memory_size: 512 # MB
      skip_cleanup: true
      on:
        condition: $CHANGED_FUNCTION

    # Deploy Drobpox Diary desktop app to github releases
    - provider: releases
      api_key: $GITHUB_API_KEY
      file: dropbox-diary-desktop/build/libs/dropbox-diary-desktop.jar
      skip_cleanup: true
      on:
        tags: true
        condition: $CHANGED_DESKTOP

  - language: node_js
    node_js:
      - "8.0.0"
    before_install:
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
      - export PATH=$HOME/.yarn/bin:$PATH
    cache:
      yarn: true
    script:
      - CHANGED_MOBILE = $(git diff --name-only HEAD^ | grep "dropbox-diary-mobile")
      - CHANGED_WEB = $(git diff --name-only HEAD^ | grep "dropbox-diary-web")
      - cd dropbox-diary-web
      - yarn
      - yarn build
      - cd ..
      - "echo ${CHANGED_MOBILE}"
      - "echo ${CHANGED_WEB}"
    deploy:
      provider: pages
      local_dir: dropbox-diary-web/build
      github_token: $GITHUB_API_KEY
      skip_cleanup: true
      on:
        condition: $CHANGED_WEB