sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_5005aee41fbb_key -iv $encrypted_5005aee41fbb_iv
  -in dropbox-diary-api/gae/client-secret.json.enc -out dropbox-diary-api/gae/client-secret.json -d
matrix:
  include:
  - language: java
    jdk: oraclejdk8
    script:
    - "./gradlew clean build"
    deploy:
    - provider: script
      script: bash dropbox-diary-api/heroku_deploy
      skip_cleanup: true
      on:
        branch: master
    - provider: releases
      api_key: "${GITHUB_API_KEY}"
      file: dropbox-diary-desktop/build/libs/dropbox-diary-desktop.jar
      skip_cleanup: true
      on:
        all_branches: true
        tags: true
