matrix:
  include:
  - language: java
    jdk: oraclejdk8
    script:
    - "./gradlew clean build"
    deploy:

    # Deploy Dropbox Diary function lib to AWS Lambda
    - provider: lambda
      function_name: dropbox-diary-function
      region: us-east-1
      role: arn:aws:iam::377159598624:role/aws-lambda-deployer # see https://docs.travis-ci.com/user/deployment/lambda/#AWS-permissions
      runtime: java8
      zip: dropbox-diary-function/build/distributions/dropbox-diary-function.zip
      module_name: kadiary # package name
      handler_name: Main # class name
      timeout: 60 # seconds
      memory_size: 512 # MB
      skip_cleanup: true
      on:
        all_branches: true

    # Deploy Drobpox Diary desktop app to github releases
    - provider: releases
      api_key: "${GITHUB_API_KEY}"
      file: dropbox-diary-desktop/build/libs/dropbox-diary-desktop.jar
      skip_cleanup: true
      on:
        all_branches: true
        tags: true