matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./gradlew clean build
      deploy:
        provider: releases
        api_key: ${GITHUB_API_KEY}
        file: "dropbox-diary-desktop/build/libs/dropbox-diary-desktop.jar"
        skip_cleanup: true
        on:
          all_branches: true
          tags: true
